
import { GoogleGenAI } from "@google/genai";

const getAIClient = () => {
  return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

export const generateResponse = async (prompt: string, history: { role: string, parts: { text: string }[] }[]) => {
  const ai = getAIClient();
  const chat = ai.chats.create({
    model: 'gemini-3-flash-preview',
    config: {
      systemInstruction: `تۆ ناڤێ تە "بیرهات AI"یە. تۆ هاریکارەکێ ژیری کو تەنێ و تەنێ ب دیالێکتێ کوردیێ بادینی (Duhok/Zakho dialect) دئاخڤی.
      
      یاسایێن تە یێن جێگیر:
      1. تەنێ بەرسفا پرسیارێن دەربارەی "موبایلان" (ئایفۆن، ئەندرۆید، کێشەیێن تەکنیکی، کڕین و فرۆتن) و "سوشیال میدیایێ" (فەیسبووک، ئینستاگرام، تیکتۆک، سناپچات، وەرگرتنەڤەیا ئەکاونتان) بدە.
      2. ئەگەر پرسیارەک دەرڤەی ڤان بواران ژ تە هاتە کرن، ب ڕێزڤە بێژە: "ببورە، بیرهاتی ئەز وەسا یێ فێر کریم کو تەنێ بەرسفا پرسیارێن دەربارەی موبایل و سوشیال میدیایێ بدەم."
      3. ب چو شێوەیان ب زمانەکێ دی یان دیالێکتەکێ دی نەئاخڤە. تەنێ بادینی یێ پەتە بکاربینە.
      4. بەرسفێن تە با کورت و زەلال و پراکتیکی بن.
      5. چو ئاماژەیەکێ ب "Gemini" یان کۆمپانیێن دەرەکی نەکە، تۆ تەنێ "بیرهات AI" ی.`,
    }
  });

  const result = await chat.sendMessage({ message: prompt });
  return result.text;
};

export const translateText = async (text: string, targetLang: 'badini' | 'english' | 'arabic') => {
  const ai = getAIClient();
  
  const langContext = {
    badini: "Pure Kurdish Badini dialect (Behdinan). Use words like 'دێ، ئەز، تە، چێبیت، هاتیە' and strictly avoid Sorani Kurdish forms like 'دەبێت، من، دەکرێت'. Ensure it sounds natural to people in Duhok and Zakho.",
    english: "Natural and professional English.",
    arabic: "Clear and standard Arabic (Fusha) or commonly understood modern Arabic."
  };

  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: {
      parts: [
        { text: `As a top-tier linguistic expert, translate the following text into ${targetLang}.
        
        CONTEXT FOR TARGET: ${langContext[targetLang]}
        
        RULES:
        - Detect the source language automatically.
        - If translating to Badini, ensure the grammar is 100% Behdinan dialect.
        - Do not add meta-comments or explanations. Only the result.
        - Preserve the original meaning and emotional weight.
        
        TEXT: "${text}"` }
      ]
    }
  });

  return response.text;
};

// Generate artistic visualizations using the gemini-2.5-flash-image model
export const generateKurdishArt = async (prompt: string) => {
  const ai = getAIClient();
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { text: `Create a beautiful artistic visualization inspired by Kurdish culture and this prompt: ${prompt}` }
      ]
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1"
      }
    }
  });

  // Iterate through parts to find the generated image data
  if (response.candidates?.[0]?.content?.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
  }
  
  throw new Error("No image was generated by the model.");
};
